### ISSUE TITLE
Check for valid variable TYPEs

### ISSUE THREAD

**Issue by DanielEWeeks** [lwheinsberg/dbGaPCheckup#9]
A data dictionary has some variables that were given the TYPE `time, encoded value`, but the `time` TYPE is not among the valid dbGaP types, as defined in the dbGaP Submission Guide:

> Data value type: integer (1,2,3,4,…), encoded value (integers or strings are coded for non-numerical meaning, ex. 1=Control; 2=Case, see VALUES), decimal (0.5,2.5,…), string (African American, Asian, Caucasian, Hispanic, Non-Hispanic). For mixed values (any combination of string, integers, decimals and/or encoded values) in a single data column, list all types present.

Similarly, some were given the TYPE `decimal, encoded valuev`, where the `encoded valuev` is a typo.

So it would be good to add a check that the unique set of TYPEs listed in the data dictionary contain only valid TYPEs.

To do so, we could use `value_meaning_table` to create a vector of all the `TYPE` values in the data dictionary, but then we'd need to split compound TYPEs like `decimal, encoded value` into their component TYPES of `decimal` and `encoded value`.

**Comment by lwheinsberg** [comment]
This check (`type_check`) already exists.

In trying to recreate the errors above, however, I encountered some strange behavior in the code. Specifically, this code: 

```
DD.dict$TYPE <- gsub("integer", " ", DD.dict$TYPE, fixed=TRUE)
DD.dict$TYPE <- gsub("decimal", " ", DD.dict$TYPE, fixed=TRUE)
DD.dict$TYPE <- gsub("encoded value", " ", DD.dict$TYPE, fixed=TRUE)
DD.dict$TYPE <- gsub("string", " ", DD.dict$TYPE, fixed=TRUE)
DD.dict$TYPE <- gsub(",", " ", DD.dict$TYPE, fixed=TRUE)
DD.dict$TYPE <- gsub(" ", NA, DD.dict$TYPE, fixed=TRUE)
```

is intended to temporarily remove (gsub out) any values that are dbGaP-allowed so that we can return any remaining values to the user as an "illegal" entry. When iterating through each line, the code works perfectly until it gets to `DD.dict$TYPE <- gsub(" ", NA, DD.dict$TYPE, fixed=TRUE)`. When the only entry remaining in my `TYPE` column is "time", this line deletes the word "time". I don't understand why that is happening. For now, I have corrected this issue with the following changes: 

```
   DD.dict$TYPE <- gsub("integer", " ", DD.dict$TYPE, fixed=TRUE)
    DD.dict$TYPE <- gsub("decimal", " ", DD.dict$TYPE, fixed=TRUE)
    DD.dict$TYPE <- gsub("encoded value", " ", DD.dict$TYPE, fixed=TRUE)
    DD.dict$TYPE <- gsub("string", " ", DD.dict$TYPE, fixed=TRUE)
    DD.dict$TYPE <- gsub(",", " ", DD.dict$TYPE, fixed=TRUE)
    DD.dict$TYPE <- trimws(DD.dict$TYPE)
    #DD.dict$TYPE <- gsub(" ", NA, DD.dict$TYPE, fixed=TRUE)
    DD.dict$TYPE[DD.dict$TYPE == ""] <- NA
```

While the updated code works as planned for a good data set: 

``
> type_check(DD.dict.A)
$Message
[1] "Passed: All TYPE entries found are accepted by dbGaP per submission instructions."

$Information
[1] "integer"                "integer, encoded value" "decimal, encoded value"
```

It returns an extra/unwanted "NA" value for a bad data set: 

```
type_check(DD_dict)
$Message
[1] "ERROR: Some TYPE entries are not allowable per dbGaP submission instructions."

$IllegalEntries
[1] "time" NA    
```

I am going to revisit this.

**Comment by DanielEWeeks** [comment]
In the man page for `gsub`, it says this about the behavior when the `replacement` parameter is set to `NA` in the `gsub` command:

>  If NA, all elements in the result corresponding to matches will be set to NA.

So, for example, here is a vector of length three where items 1 and 3 are a 'match' because they contain a space:

```
> gsub(" ",NA,c(" X","Y","Z "))
[1] NA  "Y" NA 
```

Didn't know about that quirk of `gsub`.

----

Actually, instead of replacing matches with a space like this

```
gsub("integer", " ", DD.dict$TYPE, fixed=TRUE)
```

why not replace them with the empty string like this:

```
gsub("integer", "", DD.dict$TYPE, fixed=TRUE)
```

**Comment by lwheinsberg** [comment]
> why not replace them with the empty string like this:
> 
> `gsub("integer", "", DD.dict$TYPE, fixed=TRUE)`

I just tried this, but still have the same issue with listing NA as an illegal entry. But strange because this does NOT throw an error for error-free data sets.

**Comment by lwheinsberg** [comment]
Revisiting this, I was able to correct the unwanted behavior (returning unique value of NA with failed checks) with this line: 

```
IllegalEntries <- unique(DD.dict$TYPE[!is.na(DD.dict$TYPE)]) 
```
